name: Build imgui_bundle for Win11 VS2019

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    env:
      BUILD_TYPE: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake
        uses: lukka/get-cmake@v3.27.7

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          cmake --build . --config ${{ env.BUILD_TYPE }}

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: imgui_bundle_win_vs2019
          path: |
            build/${{ env.BUILD_TYPE }}/*
            build/assets/*
            build/*.exe
            build/*.dll
            build/*.lib

      - name: List output files (debugging)
        run: |
          ls build/${{ env.BUILD_TYPE }}
