name: Build imgui_bundle for Win11 VS2022

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    env:
      BUILD_TYPE: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake
        uses: lukka/get-cmake@v3.27.7

      - name: Configure & Build
        run: |
          cmake -G "Visual Studio 17 2022" -A x64 `
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} `
                -S . -B build
          cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: List build outputs (debug)
        shell: pwsh
        run: |
          Get-ChildItem -Force build
          Get-ChildItem -Force build\bin\Release

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: imgui_bundle_win_vs2022
          path: |
            build\Release\*.exe
            build\Release\*.dll
            build\Release\*.lib
